version: '1.0.0'

services:
  influxdb:
    image: influxdb:2.7
    ports:
      - 8086:8086
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=12345678=
      - DOCKER_INFLUXDB_INIT_ORG=maybell
      - DOCKER_INFLUXDB_INIT_BUCKET=default
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2

  test-idb:
    image: influxdb:2.7
    ports:
      - 8686:8086
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=12345678=
      - DOCKER_INFLUXDB_INIT_ORG=maybell
      - DOCKER_INFLUXDB_INIT_BUCKET=default
    volumes:
      - influxdb-src-data:/var/lib/influxdb2
      - influxdb-src-config:/etc/influxdb2
  

  test-src:
    build: ./test_src
    command: python3 datamock.py
    depends_on:
      - test-idb
    environment:
      - URL=http://test-idb:8086


volumes:
  influxdb-data:
  influxdb-config:
  influxdb-src-data:
  influxdb-src-config:
