"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

class NotificationEndpointType:
    SLACK: str
    PAGERDUTY: str
    HTTP: str
    TELEGRAM: str
    openapi_types: Incomplete
    attribute_map: Incomplete
    def __init__(self) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...
